// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgieaRJIhm7kuH6DSzcLeM_V-iFQ8L8JE',
    appId: '1:1007562749528:web:b50cb96cc429107dcc3c2d',
    messagingSenderId: '1007562749528',
    projectId: 'barbarago9b',
    authDomain: 'barbarago9b.firebaseapp.com',
    storageBucket: 'barbarago9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ieugDgx5mUUU8UGn5Ajd_OhrWJ9Lr58',
    appId: '1:1007562749528:android:10004a146917cb06cc3c2d',
    messagingSenderId: '1007562749528',
    projectId: 'barbarago9b',
    storageBucket: 'barbarago9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3DB3c2NJCxUF8pFZVw3Tu1BESh9wC960',
    appId: '1:1007562749528:ios:7e0d05ee6c080a3ecc3c2d',
    messagingSenderId: '1007562749528',
    projectId: 'barbarago9b',
    storageBucket: 'barbarago9b.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3DB3c2NJCxUF8pFZVw3Tu1BESh9wC960',
    appId: '1:1007562749528:ios:7e0d05ee6c080a3ecc3c2d',
    messagingSenderId: '1007562749528',
    projectId: 'barbarago9b',
    storageBucket: 'barbarago9b.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgieaRJIhm7kuH6DSzcLeM_V-iFQ8L8JE',
    appId: '1:1007562749528:web:fd990b34168c2f54cc3c2d',
    messagingSenderId: '1007562749528',
    projectId: 'barbarago9b',
    authDomain: 'barbarago9b.firebaseapp.com',
    storageBucket: 'barbarago9b.appspot.com',
  );
}
